# Client Dataset Exploration and Cleaning

## 1. Introduction

This notebook explores and prepares the client dataset for use in buyer segmentation.

The objective is to understand client demographics, geographic characteristics, acquisition preferences, financing behavior, referral channels, and satisfaction levels.

The notebook also performs basic data cleaning and derives client age from the date of birth field.

------------

## 2. Import Libraries

The required libraries are imported for data loading, manipulation, and exploratory data analysis.

In [1]:
import pandas as pd
import numpy as np

## 3. Load the Client Dataset

The client dataset is loaded into a Pandas DataFrame for exploration and cleaning.

In [4]:
clients_df = pd.read_csv("../data/clients.csv")

clients_df

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,C0001,Individual,Kareem,Liu,05-11-1968,F,USA,California,Home,4,Yes,Website
1,C0002,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,C0003,Individual,Kale,Gay,04-07-1959,M,USA,California,Home,4,Yes,Agency
3,C0004,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,C0005,Company,Marleez,Co,2/28/1976,M,USA,California,Investment,5,No,Website
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,C1996,Individual,Samantha,Brooks,6/20/1992,F,USA,Nevada,Home,1,Yes,Website
1996,C1997,Individual,Matthew,Cox,9/27/1942,M,USA,Arizona,Home,4,Yes,Website
1997,C1998,Individual,Mark,Patterson,9/13/1963,M,USA,Virginia,Home,5,Yes,Website
1998,C1999,Individual,Lawrence,Montgomery,6/15/1944,M,USA,Ohio,Home,4,Yes,Client
1999,C2000,Individual,Amanda,James,3/24/1996,F,USA,Georgia,Home,1,Yes,Agency

## 4. Dataset Structure

The dataset structure is examined to understand the number of records, available variables, and their data types.

In [3]:
clients_df.shape

(2000, 12)

In [7]:
clients_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   client_id            2000 non-null   str
 1   client_type          2000 non-null   str
 2   first_name           2000 non-null   str
 3   last_name            2000 non-null   str
 4   date_of_birth        2000 non-null   str
 5   gender               2000 non-null   str
 6   country              2000 non-null   str
 7   region               2000 non-null   str
 8   acquisition_purpose  2000 non-null   str
 9   satisfaction_score   2000 non-null   int64
 10  loan_applied         2000 non-null   str
 11  referral_channel     2000 non-null   str
dtypes: int64(1), str(11)
memory usage: 312.6 KB

In [5]:
clients_df.columns.tolist()

['client_id',
 'client_type',
 'first_name',
 'last_name',
 'date_of_birth',
 'gender',
 'country',
 'region',
 'acquisition_purpose',
 'satisfaction_score',
 'loan_applied',
 'referral_channel']

## 5. Numerical Variable Summary

Descriptive statistics are used to examine the numerical variables, particularly satisfaction scores and other quantitative attributes.

In [8]:
clients_df.describe()

       satisfaction_score
count         2000.000000
mean             3.029000
std              1.413562
min              1.000000
25%              2.000000
50%              3.000000
75%              4.000000
max              5.000000

## 6. Missing Value Analysis

Missing values are checked across all client attributes.

This step ensures that incomplete client records are identified before feature engineering and machine learning.

In [9]:
clients_df.isnull().sum()

client_id              0
client_type            0
first_name             0
last_name              0
date_of_birth          0
gender                 0
country                0
region                 0
acquisition_purpose    0
satisfaction_score     0
loan_applied           0
referral_channel       0
dtype: int64

## 7. Duplicate Client Analysis

Duplicate rows and duplicate client IDs are checked to ensure that each client is represented uniquely in the client dataset.

The `client_id` is used as the unique identifier for linking client records with property transactions.

In [6]:
clients_df.duplicated().sum()

np.int64(0)

## 8. Categorical Variable Analysis

The unique values and frequency distributions of the major categorical variables are examined.

These variables describe buyer characteristics such as client type, gender, country, region, acquisition purpose, financing behavior, and referral channel.

Understanding these distributions is important before applying categorical encoding for machine learning.

In [8]:
clients_df['client_type'].value_counts()

client_type
Individual    1897
Company        103
Name: count, dtype: int64

In [9]:
clients_df['gender'].value_counts()

gender
M    1012
F     988
Name: count, dtype: int64

In [10]:
clients_df['country'].value_counts()

country
USA          1538
UK             95
Canada         85
Germany        56
France         53
Belgium        43
Mexico         40
Australia      39
Russia         36
Denmark        15
Name: count, dtype: int64

In [11]:
clients_df['region'].value_counts()

region
California                633
Nevada                    143
Colorado                  118
Arizona                   108
Oregon                     96
Utah                       87
Washington                 73
Virginia                   65
Texas                      56
Florida                    50
New York                   49
Georgia                    34
England                    29
Alberta                    27
Scotland                   25
Northern Ireland           24
Ohio                       24
British Columbia           20
Wales                      17
Hamburg                    16
Flanders                   16
Brittany                   16
Ile-de-France              15
Manitoba                   15
Wallonia                   15
Quebec                     14
New South Wales            13
Victoria                   13
Brussels                   12
Bavaria                    12
Berlin                     11
Krasnodar Krai             10
Saint Petersburg           10
North Rhine-Westphalia     10
Provence                   10
Nuevo Leon                 10
Ontario                     9
Jalisco                     9
Tatarstan                   8
Occitanie                   8
Mexico City                 7
Puebla                      7
Baja California             7
Hesse                       7
Western Australia           6
Capital Region              5
Novosibirsk                 5
Normandy                    4
North Denmark               4
Queensland                  4
South Australia             3
Southern Denmark            3
Moscow Oblast               3
Zealand                     2
Wyoming                     1
Kansas                      1
Central Denmark             1
Name: count, dtype: int64

In [12]:
clients_df['acquisition_purpose'].value_counts()

acquisition_purpose
Home          1385
Investment     615
Name: count, dtype: int64

In [13]:
clients_df['loan_applied'].value_counts()

loan_applied
No     1264
Yes     736
Name: count, dtype: int64

In [14]:
clients_df['referral_channel'].value_counts()

referral_channel
Website    1103
Agency      705
Client      192
Name: count, dtype: int64

### 🔍 Explore Unique Values in Categorical Columns

To understand the categories present in the dataset, we inspect the **unique values** of selected categorical columns.

This helps us:
- Identify the different categories in each feature.
- Detect unexpected or inconsistent values.
- Understand the structure of categorical variables before preprocessing and encoding.

## 9. Satisfaction Score Analysis

The distribution and descriptive statistics of `satisfaction_score` are examined.

The satisfaction score ranges from 1 to 5 and can later be used as a numerical feature during buyer segmentation.

In [16]:
clients_df['satisfaction_score'].describe()

count    2000.000000
mean        3.029000
std         1.413562
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: satisfaction_score, dtype: float64

In [17]:
clients_df['satisfaction_score'].unique()

array([4, 1, 5, 3, 2])

## 10. Date of Birth Cleaning

The `date_of_birth` column is converted from text into a proper datetime format.

The dataset contains dates represented in different formats, so mixed-format parsing is used while invalid values are converted to missing values for validation.

In [18]:
clients_df['date_of_birth'].head()

0    05-11-1968
1    11/26/1962
2    04-07-1959
3    11/25/1959
4     2/28/1976
Name: date_of_birth, dtype: str

In [19]:
clients_df['date_of_birth'].dtype

In [20]:
clients_df['date_of_birth'] = pd.to_datetime(
    clients_df['date_of_birth'],
    format='mixed',
    dayfirst=False,
    errors='coerce'
)

In [21]:
print(clients_df['date_of_birth'].dtype)
print("Invalid dates:", clients_df['date_of_birth'].isna().sum())

datetime64[us]
Invalid dates: 0

## 11. Age Feature Engineering

Age is derived from the client's date of birth using a fixed reference date.

Age is more suitable than the original date of birth for buyer segmentation because it represents a directly interpretable demographic characteristic while avoiding the use of the raw birth date as a modeling feature.

In [23]:
reference_date = pd.Timestamp('2026-01-01')

clients_df['age'] = (
    reference_date.year - clients_df['date_of_birth'].dt.year
)

In [24]:
clients_df[['date_of_birth', 'age']].head(10)

  date_of_birth  age
0    1968-05-11   58
1    1962-11-26   64
2    1959-04-07   67
3    1959-11-25   67
4    1976-02-28   50
5    1957-03-06   69
6    1947-05-24   79
7    1969-10-17   57
8    1975-10-05   51
9    1966-06-17   60

In [25]:
clients_df['age'].describe()

count    2000.000000
mean       56.099000
std        17.343719
min        26.000000
25%        41.000000
50%        57.000000
75%        71.000000
max        95.000000
Name: age, dtype: float64

In [26]:
clients_df['age'].min(), clients_df['age'].max()

(np.int32(26), np.int32(95))

In [27]:
reference_date = pd.Timestamp('2026-01-01')

clients_df['age'] = (
    (reference_date - clients_df['date_of_birth']).dt.days // 365
)

### Age Distribution

The derived age variable is examined using descriptive statistics to verify that the resulting values are reasonable and suitable for further analysis.

In [28]:
clients_df[['date_of_birth', 'age']].describe()

                    date_of_birth         age
count                        2000  2000.00000
mean   1970-05-26 02:22:33.600000    55.14700
min           1931-02-13 00:00:00    25.00000
25%           1955-12-21 12:00:00    40.00000
50%           1969-10-25 00:00:00    56.00000
75%           1985-02-19 18:00:00    70.00000
max           2000-12-19 00:00:00    94.00000
std                           NaN    17.35572

In [29]:
clients_df[['date_of_birth', 'age']].head(10)

  date_of_birth  age
0    1968-05-11   57
1    1962-11-26   63
2    1959-04-07   66
3    1959-11-25   66
4    1976-02-28   49
5    1957-03-06   68
6    1947-05-24   78
7    1969-10-17   56
8    1975-10-05   50
9    1966-06-17   59

In [30]:
clients_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   client_id            2000 non-null   str
 1   client_type          2000 non-null   str
 2   first_name           2000 non-null   str
 3   last_name            2000 non-null   str
 4   date_of_birth        2000 non-null   datetime64[us]
 5   gender               2000 non-null   str
 6   country              2000 non-null   str
 7   region               2000 non-null   str
 8   acquisition_purpose  2000 non-null   str
 9   satisfaction_score   2000 non-null   int64
 10  loan_applied         2000 non-null   str
 11  referral_channel     2000 non-null   str
 12  age                  2000 non-null   int64
dtypes: datetime64[us](1), int64(2), str(10)
memory usage: 309.5 KB

In [31]:
clients_df.head()

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel,age
0,C0001,Individual,Kareem,Liu,1968-05-11,F,USA,California,Home,4,Yes,Website,57
1,C0002,Individual,Trystan,Oconnor,1962-11-26,M,USA,California,Home,1,No,Website,63
2,C0003,Individual,Kale,Gay,1959-04-07,M,USA,California,Home,4,Yes,Agency,66
3,C0004,Individual,Russell,Gross,1959-11-25,M,USA,California,Home,5,No,Website,66
4,C0005,Company,Marleez,Co,1976-02-28,M,USA,California,Investment,5,No,Website,49

## 12. Key Findings

The client dataset contains 2,000 unique clients with no missing values in the original client attributes.

The dataset includes demographic, geographic, acquisition, financing, referral, and satisfaction information.

The date of birth field was successfully converted to datetime format, and age was derived as a new numerical feature.

Personal identifiers such as first and last names are retained only in the original dataset and will not be used as machine learning features.

The cleaned client information is now ready to be integrated with property-level transaction information.