In [2]:
import pandas as pd
import numpy as np

clients_df = pd.read_csv("../data/clients.csv")

clients_df

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,C0001,Individual,Kareem,Liu,05-11-1968,F,USA,California,Home,4,Yes,Website
1,C0002,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,C0003,Individual,Kale,Gay,04-07-1959,M,USA,California,Home,4,Yes,Agency
3,C0004,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,C0005,Company,Marleez,Co,2/28/1976,M,USA,California,Investment,5,No,Website
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,C1996,Individual,Samantha,Brooks,6/20/1992,F,USA,Nevada,Home,1,Yes,Website
1996,C1997,Individual,Matthew,Cox,9/27/1942,M,USA,Arizona,Home,4,Yes,Website
1997,C1998,Individual,Mark,Patterson,9/13/1963,M,USA,Virginia,Home,5,Yes,Website
1998,C1999,Individual,Lawrence,Montgomery,6/15/1944,M,USA,Ohio,Home,4,Yes,Client
1999,C2000,Individual,Amanda,James,3/24/1996,F,USA,Georgia,Home,1,Yes,Agency

In [3]:
clients_df.shape

(2000, 12)

In [4]:
clients_df.isnull().sum()

client_id              0
client_type            0
first_name             0
last_name              0
date_of_birth          0
gender                 0
country                0
region                 0
acquisition_purpose    0
satisfaction_score     0
loan_applied           0
referral_channel       0
dtype: int64

In [5]:
clients_df.columns.tolist()

['client_id',
 'client_type',
 'first_name',
 'last_name',
 'date_of_birth',
 'gender',
 'country',
 'region',
 'acquisition_purpose',
 'satisfaction_score',
 'loan_applied',
 'referral_channel']

In [6]:
clients_df.duplicated().sum()

np.int64(0)

In [7]:
clients_df['client_id'].duplicated().sum()

np.int64(0)

In [13]:
clients_df['client_type'].value_counts()

client_type
Individual    1897
Company        103
Name: count, dtype: int64

In [15]:
clients_df['gender'].value_counts()

gender
M    1012
F     988
Name: count, dtype: int64

In [14]:
clients_df['country'].value_counts()

country
USA          1538
UK             95
Canada         85
Germany        56
France         53
Belgium        43
Mexico         40
Australia      39
Russia         36
Denmark        15
Name: count, dtype: int64

In [16]:
clients_df['region'].value_counts()

region
California                633
Nevada                    143
Colorado                  118
Arizona                   108
Oregon                     96
Utah                       87
Washington                 73
Virginia                   65
Texas                      56
Florida                    50
New York                   49
Georgia                    34
England                    29
Alberta                    27
Scotland                   25
Northern Ireland           24
Ohio                       24
British Columbia           20
Wales                      17
Hamburg                    16
Flanders                   16
Brittany                   16
Ile-de-France              15
Manitoba                   15
Wallonia                   15
Quebec                     14
New South Wales            13
Victoria                   13
Brussels                   12
Bavaria                    12
Berlin                     11
Krasnodar Krai             10
Saint Petersburg           10
North Rhine-Westphalia     10
Provence                   10
Nuevo Leon                 10
Ontario                     9
Jalisco                     9
Tatarstan                   8
Occitanie                   8
Mexico City                 7
Puebla                      7
Baja California             7
Hesse                       7
Western Australia           6
Capital Region              5
Novosibirsk                 5
Normandy                    4
North Denmark               4
Queensland                  4
South Australia             3
Southern Denmark            3
Moscow Oblast               3
Zealand                     2
Wyoming                     1
Kansas                      1
Central Denmark             1
Name: count, dtype: int64

In [17]:
clients_df['acquisition_purpose'].value_counts()

acquisition_purpose
Home          1385
Investment     615
Name: count, dtype: int64

In [18]:
clients_df['loan_applied'].value_counts()

loan_applied
No     1264
Yes     736
Name: count, dtype: int64

In [19]:
clients_df['referral_channel'].value_counts()

referral_channel
Website    1103
Agency      705
Client      192
Name: count, dtype: int64

In [ ]:
clients_df.head(10)

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,C0001,Individual,Kareem,Liu,05-11-1968,F,USA,California,Home,4,Yes,Website
1,C0002,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,C0003,Individual,Kale,Gay,04-07-1959,M,USA,California,Home,4,Yes,Agency
3,C0004,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,C0005,Company,Marleez,Co,2/28/1976,M,USA,California,Investment,5,No,Website
5,C0006,Individual,Yurem,Wright,03-06-1957,M,USA,California,Home,3,Yes,Website
6,C0007,Individual,Xavier,Faulkner,5/24/1947,M,Canada,Quebec,Investment,5,No,Website
7,C0008,Individual,Kayden,Olsen,10/17/1969,F,USA,California,Home,5,No,Website
8,C0009,Individual,Joaquin,Mullins,10-05-1975,M,USA,California,Investment,5,No,Agency
9,C0010,Individual,Nicolas,Navarro,6/17/1966,M,USA,Oregon,Investment,3,No,Agency

In [21]:
clients_df['satisfaction_score'].describe()

count    2000.000000
mean        3.029000
std         1.413562
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: satisfaction_score, dtype: float64

In [23]:
clients_df['satisfaction_score'].describe()

count    2000.000000
mean        3.029000
std         1.413562
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: satisfaction_score, dtype: float64

In [24]:
clients_df['date_of_birth'].head()

0    05-11-1968
1    11/26/1962
2    04-07-1959
3    11/25/1959
4     2/28/1976
Name: date_of_birth, dtype: str